version: "2"

services:
  apache-php:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    image: apache-php:1.0
    container_name: apache-php
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/logs
    ports:
      - "8080:80"
    environment:
      environment: "development"
    networks:
      - back-tier

  mysql:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: mysql:1.0
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
    networks:
      - back-tier

networks:
  back-tier:
