version: "2"

services:
  apache_2.4.10-php_7.0.3:
    build:
      context: .
      dockerfile: ./apache/Dockerfile
    image: apache_2.4.10-php_7.0.3:1.0
    container_name: apache_2.4.10-php_7.0.3
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/logs
    ports:
      - "8080:80"
    environment:
      environment: "development"
    networks:
      - back-tier

  mysql_5.7.10:
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: mysql_5.7.10:1.0
    container_name: mysql_5.7.10
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: xxxxx
    networks:
      - back-tier

networks:
  back-tier:
